first =int(input("Enter Integer"))
print("Entered Integer:",first)
print(format(id(first), 'x'))
second = input("Enter String:")
print("Entered String : ",second)
print(format(id(second), 'X')) 
